# Generated by Django 4.0.3 on 2022-07-28 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
