# Generated by Django 4.0.3 on 2022-08-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': '10. Reviews'},
        ),
    ]
