# Generated by Django 4.0.3 on 2022-09-02 16:57

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddressbook',
            old_name='address',
            new_name='apartment_address',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.useraddressbook'),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='country',
            field=django_countries.fields.CountryField(default='USA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='payment_option',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='street_address',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='zip_code',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
