# Generated by Django 4.0.3 on 2022-09-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_address_useraddressbook_apartment_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddressbook',
            old_name='apartment_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='useraddressbook',
            name='country',
        ),
        migrations.RemoveField(
            model_name='useraddressbook',
            name='payment_option',
        ),
        migrations.RemoveField(
            model_name='useraddressbook',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='useraddressbook',
            name='zip_code',
        ),
    ]
